[tool.poetry]
name = "recording-for-repairs"
version = "0.1.0"
description = ""
authors = ["feudall <joker13joker@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
